/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biodata;

/**
 *
 * @author LLeNz
 */
public class Biodataa extends javax.swing.JFrame {

    
    String nama,nim,hobi,jeniskelamin,alamat;
    public Biodataa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        txtnama = new javax.swing.JLabel();
        txttnama = new javax.swing.JTextField();
        txtjeniskelamin = new javax.swing.JLabel();
        txttjeniskelamin = new javax.swing.JComboBox<>();
        txtalamat = new javax.swing.JLabel();
        txtbutton = new javax.swing.JButton();
        txthapus = new javax.swing.JButton();
        txtoutput = new javax.swing.JScrollPane();
        txtthasil = new javax.swing.JTextArea();
        txtnim = new javax.swing.JLabel();
        txttnim = new javax.swing.JTextField();
        txthobi = new javax.swing.JLabel();
        txtthobi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txttalamat = new javax.swing.JTextArea();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane1.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtnama.setText("Nama                :");

        txttnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnamaActionPerformed(evt);
            }
        });

        txtjeniskelamin.setText("Jenis Kelamin   :");

        txttjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "L" }));
        txttjeniskelamin.setToolTipText("");
        txttjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttjeniskelaminActionPerformed(evt);
            }
        });

        txtalamat.setText("Alamat              :");

        txtbutton.setText("Prosses");
        txtbutton.setToolTipText("");
        txtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuttonActionPerformed(evt);
            }
        });

        txthapus.setText("Hapus");
        txthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthapusActionPerformed(evt);
            }
        });

        txtthasil.setColumns(20);
        txtthasil.setRows(5);
        txtoutput.setViewportView(txtthasil);

        txtnim.setText("NIM                   :");

        txttnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnimActionPerformed(evt);
            }
        });

        txthobi.setText("Hobi                  :");

        txttalamat.setColumns(20);
        txttalamat.setRows(5);
        jScrollPane2.setViewportView(txttalamat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txttjeniskelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtthobi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txttnim, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txttnama, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthobi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtjeniskelamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtbutton)
                                        .addGap(31, 31, 31)
                                        .addComponent(txthapus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama)
                    .addComponent(txttnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnim)
                    .addComponent(txttnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthobi)
                    .addComponent(txtthobi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjeniskelamin)
                    .addComponent(txttjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtalamat)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbutton)
                    .addComponent(txthapus))
                .addGap(18, 18, 18)
                .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnamaActionPerformed

    private void txttjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttjeniskelaminActionPerformed

    private void txthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthapusActionPerformed
        // TODO add your handling code here:
        txttnama.setText("");
        txttnim.setText("");
        txtthobi.setText("");
        txttjeniskelamin.setSelectedItem("");
        txttalamat.setText("");
        
        txtthasil.setText("");
    }//GEN-LAST:event_txthapusActionPerformed

    private void txttnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnimActionPerformed

    private void txtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuttonActionPerformed
        // TODO add your handling code here:
        nama = txttnama.getText();
        nim = txttnim   .getText();
        hobi = txtthobi.getText();
        jeniskelamin = txttjeniskelamin.getSelectedItem().toString();
        alamat = txttalamat.getText();
        
        txtthasil.setText("Nama \t   = " + nama + "\nNIM \t = " + nim + "\nHobi \t = " + hobi + "\nJeniskelamin \t = " + jeniskelamin + "\nAlamat \t = " + alamat);
    }//GEN-LAST:event_txtbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biodataa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biodataa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biodataa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biodataa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biodataa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel txtalamat;
    private javax.swing.JButton txtbutton;
    private javax.swing.JButton txthapus;
    private javax.swing.JLabel txthobi;
    private javax.swing.JLabel txtjeniskelamin;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtnim;
    private javax.swing.JScrollPane txtoutput;
    private javax.swing.JTextArea txttalamat;
    private javax.swing.JTextArea txtthasil;
    private javax.swing.JTextField txtthobi;
    private javax.swing.JComboBox<String> txttjeniskelamin;
    private javax.swing.JTextField txttnama;
    private javax.swing.JTextField txttnim;
    // End of variables declaration//GEN-END:variables
}
